# Generated by Django 4.2.9 on 2024-01-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffuser',
            old_name='ID',
            new_name='staff_id',
        ),
    ]
