# Generated by Django 4.2.9 on 2024-01-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportApp', '0002_rename_id_staffuser_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='is_transport_officer',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='to_date',
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
