# Generated by Django 4.2.9 on 2024-01-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportApp', '0003_remove_staffuser_from_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='staff_id',
        ),
    ]
