# Generated by Django 4.2.9 on 2024-01-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportApp', '0004_remove_staffuser_staff_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffUser',
        ),
    ]
