# Generated by Django 4.2.9 on 2024-01-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportApp', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
